spring.application.name=certitrack-backend
spring.datasource.url=jdbc:mysql://localhost:3306/certitrack
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.application.name=certitrack-backend

# MySQL (Railway Cloud Database)
spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:46753/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=qNdsseTcZJsgcKMoavJxgnmABjVipfLB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server (IMPORTANT for deployment)
server.port=${PORT:8080}

# Optional (better logging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
